server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh               #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001      #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE      #lb为uri的协议，表示启用gateway的负载均衡功能
          predicates:                     #断言，路由相匹配的进行路由
            - Path=/payment/get/**
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE      #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**              #断言，路径相匹配的进行路由
            - After=2021-04-12T22:56:59.302+08:00[Asia/Shanghai]    #过了这个时间后才能进行路由
#            - Cookie=username,\d+            #请求要带有cookie，两个参数，一个是cookiename(key)，一个是正则表达式(value)，cookiename和正则表达式都匹配上则进行路由
#            - Header=X-Request-Id,\d+        #请求头中要有相应的属性，第一个参数是属性名，第二个参数是属性值
      discovery:
        locator:
          enabled: true    #开启从注册中心动态动态创建路由的功能，利用微服务名进行路由
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    hostname: cloud-gateway-service