server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.1.122
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}