server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiushigao/springcloud-config.git  #github上的仓库名称
          #搜索目录
          search-paths:
            - springcloud-config
          username: 2836428900@qq.com
          password: wangjie037413
      #读取的git分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
